services:
  - type: web
    name: trude-app
    env: node
    rootDir: .
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm run start:render
    autoDeploy: true
